import sqlite3 as sq

async def db_connect() -> None:
	global db, cur

	db = sq.connect('criminal_database.db')
	cur = db.cursor()

	cur.execute("CREATE TABLE IF NOT EXISTS crimes (Article TEXT, nazva TEXT, Year TEXT, ChapterTXT TEXT, ACC TEXT, SUSP TEXT, TOCRT TEXT, INDICM TEXT, REL TEXT, MED TEXT, EDU TEXT, STPTOT TEXT, STPIL TEXT, STPLOC TEXT, STPSDR TEXT, STPFOR TEXT, RECID TEXT, 'GROUP' TEXT, INTOX TEXT, JUVEN TEXT, CLOSE TEXT, 'CL1.2' TEXT, 'CL3.1' TEXT, CL10 TEXT, NODEC TEXT, CRTOT TEXT, CONVIC TEXT, ACQUIT TEXT, CMED TEXT, CCLOSE TEXT, CONFES TEXT, RECONC TEXT, CIRCUMS TEXT, SPONS TEXT, AMNESTY TEXT, DEATH TEXT, COTHER TEXT, SAMEVERD TEXT, CNOTCR TEXT, DENOPR TEXT, CEDU TEXT, RELTOT TEXT, PROB TEXT, RELAMN TEXT, RELOTHR TEXT, IMPTOT TEXT, LIFEIMP TEXT, IMP TEXT, IMP1 TEXT, IMP12 TEXT, IMP23 TEXT, IMP35 TEXT, IMP510 TEXT, IMP1015 TEXT, IMP1525 TEXT, RESTOL TEXT, DISBAT TEXT, ARREST TEXT, CORRW TEXT, SRVRSTR TEXT, PUBLW TEXT, FINE TEXT, DEPR TEXT, G2 TEXT, G3 TEXT, G4 TEXT, G5 TEXT, G6 TEXT, G7 TEXT, G8 TEXT, G9 TEXT, G10 TEXT, G11 TEXT, G12 TEXT, G13 TEXT, G14 TEXT, G15 TEXT, G16 TEXT, G17 TEXT, G18 TEXT, G19 TEXT, G20 TEXT, G21 TEXT, G22 TEXT, G23 TEXT, G24 TEXT, G25 TEXT, G26 TEXT, G27 TEXT, G28 TEXT, G29 TEXT, G30 TEXT, G31 TEXT, G33 TEXT, G34 TEXT, G185 TEXT, G187 TEXT, G35 TEXT, G36 TEXT, G37 TEXT, G38 TEXT, G39 TEXT, G40 TEXT, G41 TEXT, G42 TEXT, G43 TEXT, G45 TEXT, G46 TEXT, G47 TEXT, G48 TEXT, G49 TEXT, G50 TEXT, G51 TEXT, G52 TEXT, G53 TEXT, G54 TEXT, G55 TEXT, G56 TEXT, G57 TEXT, G58 TEXT, G59 TEXT, G60 TEXT, G61 TEXT, G63 TEXT, G64 TEXT)")
	db.commit()

sql_query="SELECT ACC FROM data_from_table WHERE Article = 115 AND Year = 2021"
def find_rows(sql_query):
	db = sq.connect('criminal_database.db')
	cur = db.cursor()
	cur.execute(fr"{sql_query}")
	my_response = [[description[0] for description in cur.description] ] + cur.fetchall()

	if not my_response:
		pass
	print(my_response)
	return my_response


